name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  hello-world:
    runs-on: [self-hosted, bitrise]
    steps:
      - uses: actions/checkout@v3
      - run: echo "hello world"
